spring:
  datasource:
    url: "jdbc:mysql://127.0.0.1:3306/tracking?useUnicode=true&useSSL=false&characterEncoding=utf8&nullNamePatternMatchesAll=true"
    username: "${DB_USER:rewe}"
    password: "${DB_PASSWORD:}"
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      # see https://github.com/brettwooldridge/HikariCP#configuration-knobs-baby
      connection-init-sql: "SET NAMES utf8mb4 COLLATE utf8mb4_unicode_ci;"
      idle-timeout: 45000
      max-lifetime: 60000
      maximum-pool-size: 10
      minimum-idle: 3
      transaction-isolation: "TRANSACTION_READ_COMMITTED"
      validation-timeout: 5000
